Purchase orders: Support it
iFixit/checkout-ui-extensions pull request #19
Opened 2023-08-24 21:58 UTC by rickisXP

Closes https://github.com/iFixit/checkout-ui-extensions/issues/1

Summary
--
WIP

2023-08-30 20:01 UTC, masonmcelvain requested changes
CR ✌🏻 This looks really close nice work!

> Currently, if a user selects the Purchase Order option at checkout, fills in the Purchase Order field, then switches to a different payment option, the order will have the purchase order attribute with a value of ''. It seems like there isn't any way to remove an attribute once it's been applied. Is this fine?

I don't see a way around this either., since the value has to be a string. Probably fine for now.

> To check if the payment method is Purchase Order, I am checking if the payment type is of manualPayment. Is it possible in the future that we will have other custom payment methods that have the type manualPayment?

I think this is a risky thing to rely on, because we could add a new manual payment method like Bank Order or something.

I see that each payment method has a [handle](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/react-hooks/payments/useselectedpaymentoptions). Maybe we can log this and see if we can come up with a way to uniquely identify purchase orders based on it?

dev_block ✌🏻

2023-08-30 20:07 UTC, rickisXP commented
dev_block :star: Let's get the latest API merged in before we continue this

2023-08-31 05:41 UTC, rickisXP commented
> I see that each payment method has a [handle](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/react-hooks/payments/useselectedpaymentoptions). Maybe we can log this and see if we can come up with a way to uniquely identify purchase orders based on it?

I went ahead and logged `PaymentOption`, and it seems there isn't a great way to figure out purchase orders. The documentation also mentions "It may be an identifier specific to the given checkout session or the current shop," so this value could definitely change.

![image](https://github.com/iFixit/checkout-ui-extensions/assets/95708883/fe67ffc2-14c0-4857-aa07-0e3d872f2d31)

2023-08-31 15:31 UTC, masonmcelvain commented
> I went ahead and logged PaymentOption, and it seems there isn't a great way to figure out purchase orders. The documentation also mentions "It may be an identifier specific to the given checkout session or the current shop," so this value could definitely change.

Dang. `manualPayment` may be our only option for now. Thanks for checking it!

2023-08-31 15:45 UTC, masonmcelvain reviewed
More thoughts, sorry for the back and forth.

2023-08-31 15:45 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/PurchaseOrder.tsx
> +      }
Let's unconditionally report the error just in case

```suggestion
      } catch (error) {
         console.error(error);
      }
```

2023-08-31 15:45 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/PurchaseOrder.tsx
> +         applyAttributeChange({
The [docs](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/apis/checkoutapi#properties-propertydetail-applyattributechange) make it seem like the error state doesn't throw an exception, but rather returns an object like `{ type: 'error', message: 'there was a problem' }`.

Did you see an error get thrown in practice? If not, maybe we don't need the try/catch after all, apologies for suggesting it.

![image](https://github.com/iFixit/checkout-ui-extensions/assets/52104630/687a6072-3ee6-4418-98a0-8340ff41224d)

2023-08-31 15:45 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/PurchaseOrder.tsx
> +   }
I'm curious why you chose to add a new `hasAttribute` state instead of adding `applyPurchaseOrderChange` to the dependency array?

If we're going to add it to the dependency array, I think we should wrap `applyPurchaseOrderChange` in [`useCallback`](https://react.dev/reference/react/useCallback).

```
const applyPurchaseOrderChange = useCallback((value: string) => { ... }, [applyAttributeChange]);
```

2023-08-31 18:54 UTC, rickisXP commented on extensions/ui-extension/src/fields/PurchaseOrder.tsx
> +         applyAttributeChange({
I wasn't able to get an error reported in testing, but I think you're right that it returns an object.

2023-08-31 21:07 UTC, rickisXP commented on extensions/ui-extension/src/fields/PurchaseOrder.tsx
> +   }
I decided to remove it because I think it was re-rendering infinitely. I also realized that this implementation would also add the Purchase Order attribute to an order regardless of whether it already had it or not. I went ahead and kept it like this, but feel free to suggest another way of doing this.

I also left `hasAttribute` as a state, but I'm not confident that it needs to be a state.

2023-09-01 16:57 UTC, rickisXP commented
un_dev_block :star:

2023-09-01 17:47 UTC, masonmcelvain approved these changes
CR ✌🏻

2023-09-01 18:17 UTC, rickisXP commented
Thanks for the help @masonmcelvain! :rocket:

2023-09-01 18:58 UTC, erinemay commented
QA 👍 I'm seeing my test PO input showing up on the order in the admin interface
![image](https://github.com/iFixit/checkout-ui-extensions/assets/72166715/a42e6f3b-f07d-402a-91be-bbdda51b6052)

deploy_block 🌵 
I never saw the purchase order attribute on the thank you page, even on the first page load.

2023-09-01 20:13 UTC, rickisXP commented
> I never saw the purchase order attribute on the thank you page, even on the first page load.

@erinemay Good catch and sorry about that! We forgot to add the extension targets for those locations. They should show up now un_deploy_block :+1:

2023-09-01 21:05 UTC, masonmcelvain approved these changes
CR ✌🏻

Looking at this again, Shopify seems to [encourage](https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/apis/extensiontargets) declaring the `reactExtension(...)` for each component in the file the component is defined in, as opposed to a common index file.

Let's not do it in this pull since it's so close to being ready, but maybe we could consider refactoring eventually to reduce boilerplate.

```toml
api_version = "2023-07"
[[extensions]]
name = "My checkout extension"
handle = "checkout-ui"
type = "ui_extension"
[[extensions.targeting]]
target = "purchase.checkout.actions.render-before"
module = "./Actions.jsx"
[[extensions.targeting]]
target = "purchase.checkout.delivery-address.render-before"
module = "./Delivery.jsx"
[[extensions.targeting]]
target = "purchase.checkout.shipping-option-list.render-after"
module = "./ShippingOptions.jsx"
[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./Block.jsx"
```

2023-09-05 15:49 UTC, erinemay commented
dev_block 🌵 merge conflicts

2023-09-05 20:04 UTC, masonmcelvain requested changes

2023-09-05 20:04 UTC, masonmcelvain commented on extensions/ui-extension/src/index.tsx
> +reactExtension('purchase.checkout.block.render', () => <CodiceFiscale />);
This is a duplicate line from above (line 9)

2023-09-05 20:36 UTC, rickisXP commented on extensions/ui-extension/src/index.tsx
> +reactExtension('purchase.checkout.block.render', () => <CodiceFiscale />);
Oops, missed that in the merge conflict!

2023-09-05 20:36 UTC, rickisXP commented
un_dev_block :star:

2023-09-05 20:37 UTC, masonmcelvain approved these changes
CR ✌🏻

2023-09-05 21:23 UTC, erinemay commented
QA 👍 
I'm seeing it on the checkout screen as well as in admin in the order details. No errors while testing.
![image](https://github.com/iFixit/checkout-ui-extensions/assets/72166715/2a51795b-7c49-4404-bcba-1c6478844c60)
![image](https://github.com/iFixit/checkout-ui-extensions/assets/72166715/d2c1b11c-3bb2-4cdf-87e2-94fd03d4ee01)

2023-09-05 21:42 UTC, merged