Add newsletter subscription
iFixit/checkout-ui-extensions pull request #23
Opened 2023-09-13 22:12 UTC by rickisXP

closes https://github.com/iFixit/checkout-ui-extensions/issues/17

WIP

2023-10-04 21:47 UTC, kthaler commented
QA 🦕 

I am able to see the newsletter subscription in [purchase.thank-you.block.render](https://infringement-holly-cp-decades.trycloudflare.com/extensions/dev-c20f561b-8e2f-486b-bf48-db3dc5027dd0/purchase.thank-you.block.render) EX:

![Screenshot 2023-10-04 at 2 42 13 PM](https://github.com/iFixit/checkout-ui-extensions/assets/145375039/415d34ac-83f5-42d3-a39c-8e0f82454e31)

deploy_block 🦖 

but am unable to see it in [App home](https://ifixit-checkout-test.myshopify.com/admin/oauth/redirect_from_cli?client_id=c989dfd07305245037513614019e523e) EX:

![Screenshot 2023-10-04 at 2 43 34 PM](https://github.com/iFixit/checkout-ui-extensions/assets/145375039/50566ff2-6065-4aea-b9d8-3b69bb1e6f74)

though i am new to this and may be doing something wrong on my end, but I followed these steps 
>Click the App Home link in the preview console
Click Online Store in the left menu
On the current theme, click Customize
In the top middle-right dropdown, click Checkout
Click the dropdown in the top middle and click Order Status
You should be able to see the component on the order status page.

2023-10-04 23:11 UTC, rickisXP commented
> though i am new to this and may be doing something wrong on my end, but I followed these steps

@kthaler Looks like you did the right thing, I just forgot to push changes that added this component to the order status page. Sorry! Note that the instructions have changed to test the component showing on `order status`.

2023-10-05 17:03 UTC, jordycosta commented
QA 🟢 

Looks good to me!

> Newsletter subscription component is rendered on both the **Thank you** and **Order Status** page 👍 
> Using the component utilizes the iFixit subscribe API (view below)

https://github.com/iFixit/checkout-ui-extensions/assets/95656772/cf55fdda-8e68-460f-ac89-15b57431dc42

2023-10-05 20:31 UTC, rickisXP commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +const ifixit_base_url = 'https://www.ifixit.com';
We should probably come up with a way to make local testing use `cominor`

2023-10-05 22:52 UTC, masonmcelvain requested changes
CR 👏🏻 This is a great start! dev_block ✌🏻 on a couple ideas

2023-10-05 22:52 UTC, masonmcelvain commented on extensions/ui-extension/locales/de.json
> +   },
We'll want to translate these eventually but it's fine for now

2023-10-05 22:52 UTC, masonmcelvain commented on extensions/ui-extension/src/ThankYouBlock.tsx
> +   </>
We might want to use a [`<BlockStack>`](https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/components/structure/blockstack) eventually so we don't need to keep adding `<BlockSpacer>`'s, but this is fine for now

2023-10-05 22:52 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +}
Let's not do email validation, and let the html and server handle it for us

2023-10-05 22:52 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +                  />
```suggestion
                  <TextField
                     label={field_label}
                     type="email"
                     onChange={(value) => (email = value)}
                     error={validationError}
                     onInput={() => setValidationError('')}
                  />
```
https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/components/forms/textfield#textfieldprops-propertydetail-type

2023-10-05 22:52 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +               <Grid columns={['80%', '20%']} spacing="base">
An [`<InlineLayout>`](https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/components/structure/inlinelayout) might be simpler and just as effective as a Grid here

2023-10-05 22:52 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +                     onChange={(value) => (email = value)}
```suggestion
                     onChange={(value) => setEmail(value)}
```

2023-10-05 22:52 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +   let email = '';
The email should be state unless there's a good reason not to

```suggestion
   const [email, setEmail] = useState('');
```

2023-10-05 22:52 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +   };
It would be nice to use something like [ReactQuery](https://tanstack.com/query/v3/docs/react/guides/queries) to dedupe these requests

2023-10-05 22:52 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +            setShowEntryBox(false);
This seems wrong, if the request fails the user should be allowed to retry submitting their email

2023-10-05 22:52 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +const ifixit_base_url = 'https://www.ifixit.com';
This should be an [extension setting](https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/configuration#settings-definition), not hardcoded in our app.

2023-10-09 20:52 UTC, masonmcelvain commented
After thinking about https://github.com/iFixit/checkout-ui-extensions/pull/23#discussion_r1348074710 again, we can definitely do this in a followup pull, since what you have here seems like it works. Feel free to make an issue for it, and we can deal with it down the line.

2023-10-09 21:31 UTC, rickisXP commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +}
Currently, it seems like the backend returns a success even if the email isn't valid, though an invalid email isn't subscribed. I'm working on a connecting pull right now to address that

2023-10-09 21:40 UTC, rickisXP commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +}
https://github.com/iFixit/ifixit/pull/50155

2023-10-09 21:45 UTC, rickisXP commented on extensions/ui-extension/src/ThankYouBlock.tsx
> +   </>
[e87761f](https://github.com/iFixit/checkout-ui-extensions/pull/23/commits/e87761f353165aba8fd406715c2c0d087f9bd5ff)

2023-10-09 21:46 UTC, rickisXP commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +const ifixit_base_url = 'https://www.ifixit.com';
[14c5ad6](https://github.com/iFixit/checkout-ui-extensions/pull/23/commits/14c5ad6eab106a81265b4d483977bffab9b7b490)

2023-10-09 22:14 UTC, rickisXP commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +            setShowEntryBox(false);
[94a03af](https://github.com/iFixit/checkout-ui-extensions/pull/23/commits/94a03af61e63cfe78469e0b57356d95706ade43e)

2023-10-09 22:14 UTC, rickisXP commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +   };
Will open an issue for this when merged :crossed_fingers:

2023-10-09 22:15 UTC, rickisXP commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +}
[94a03af](https://github.com/iFixit/checkout-ui-extensions/pull/23/commits/94a03af61e63cfe78469e0b57356d95706ade43e)

2023-10-09 22:24 UTC, rickisXP commented
un_dev_block :star: should be good to go now!

2023-10-09 22:40 UTC, masonmcelvain submitted a review, later dismissed
CR 👏🏻  Thanks for the changes @rickisXP!

2023-10-09 22:40 UTC, masonmcelvain commented on extensions/ui-extension/src/fields/Newsletter.tsx
> +}
Minor: unused function and const

2023-10-09 23:16 UTC, erinemay commented
dev_block 🌵 @rickisXP, I'm not seeing the newsletter component. 

1. I'm on add-newsletter-subscription at https://github.com/iFixit/checkout-ui-extensions/pull/23/commits/94a03af61e63cfe78469e0b57356d95706ade43e
2. Ran `pnpm i`, then `pnpm dev`
3. Pulled up the preview console without issue
4. Clicked on the `purchase.thank-you.block.render` link and added the `placement-reference=OrderStatus3` param. I tried once adding it to the params already on the url, and replacing them with this one.
![image](https://github.com/iFixit/checkout-ui-extensions/assets/72166715/50e3d5fa-2e88-4f84-bdd3-25444706a738)
5. Went through the order. 

This is the thank you page I'm seeing.
![image](https://github.com/iFixit/checkout-ui-extensions/assets/72166715/cbd214ea-0c13-42ea-bef7-d59b6d4b4c7b)


I had to "re-stock" that [standard purchase test product](https://admin.shopify.com/store/ifixit-checkout-test/products/8383297225010) because it was oos, but I don't think that should affect this.

2023-10-10 02:29 UTC, rickisXP commented
> 4\. Clicked on the `purchase.thank-you.block.render` link and added the `placement-reference=OrderStatus3` param. I tried once adding it to the params already on the url, and replacing them with this one.

So I mistakenly looked at the wrong page on Shopify's documentation and copied the wrong thing. The param should be `?placement-reference=ORDER_STATUS3`. In Shopify's diagrams, they use camel casing, but the actual parameter uses all caps and underscores... :face_with_spiral_eyes: 

un_dev_block :camel:

2023-10-10 14:20 UTC, masonmcelvain approved these changes
CR 👏🏻

2023-10-10 20:35 UTC, deltuh-vee commented
I'm having trouble with completing an order. Do we need to setup the [Bogus Gateway or enable test mode](https://help.shopify.com/en/partners/dashboard/managing-stores/test-orders-in-dev-stores) for ifixit-checkout-test?

![CleanShot 2023-10-10 at 13 33 53](https://github.com/iFixit/checkout-ui-extensions/assets/5289715/cdfd7e12-b834-4118-90bb-0c0b188f08f8)

2023-10-10 20:40 UTC, masonmcelvain commented
Did you try these credit card numbers @deltuh-vee?

![image](https://github.com/iFixit/checkout-ui-extensions/assets/52104630/a6a0c712-ee8f-4c5a-94bd-5d5d8a388968)

2023-10-10 20:51 UTC, deltuh-vee commented
dev_block ✊ 
I'm still not seeing the component show up after completing an order and using `placement-reference=ORDER_STATUS3`.
![CleanShot 2023-10-10 at 13 48 02](https://github.com/iFixit/checkout-ui-extensions/assets/5289715/0d30fbff-86b7-4f8c-bffe-ecb4bbc496bd)

2023-10-11 18:43 UTC, rickisXP commented
> I'm still not seeing the component show up after completing an order and using `placement-reference=ORDER_STATUS3`.

I'm still able to see the component with the URL param. Note that this should show up on the bottom of the page, not the top
![image](https://github.com/iFixit/checkout-ui-extensions/assets/95708883/2854a4cc-31ea-4fa7-b042-44f3d04b75d0)

2023-10-11 20:05 UTC, deltuh-vee commented
QA 🎬 
I see that newsletter subscription component and it looks like it's working.
![CleanShot 2023-10-11 at 13 03 44](https://github.com/iFixit/checkout-ui-extensions/assets/5289715/8f821107-8cd5-4b6c-8506-0cd2f0183f65)
I skipped the url change step in the QA notes.

2023-10-11 20:17 UTC, merged